force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module_Response__c/Module_Response__c.object-meta.xml
<CustomObject>
    <label>Module Response</label>
    <nameField>
        <displayFormat>MR-{0000}</displayFormat>
        <label>Module Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Module Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module_Response__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Module Responses</relationshipLabel>
    <relationshipName>Module_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/Question_Response__c.object-meta.xml
<CustomObject>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{0000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Response__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Responses</relationshipLabel>
    <relationshipName>Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/fields/Unit_Response__c.field-meta.xml
<CustomField>
    <fullName>Unit_Response__c</fullName>
    <label>Unit Response</label>
    <referenceTo>Unit_Response__c</referenceTo>
    <relationshipLabel>Question Responses</relationshipLabel>
    <relationshipName>Question_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Unit_Response__c/Unit_Response__c.object-meta.xml
<CustomObject>
    <label>Unit Response</label>
    <nameField>
        <label>Unit Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Response__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Answered</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit_Response__c/fields/Tries__c.field-meta.xml
<CustomField>
    <fullName>Tries__c</fullName>
    <label>Tries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit_Response__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Responses</relationshipLabel>
    <relationshipName>Unit_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Response__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Unit_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/test.cls
public class test {
   public static void createUnitResponse(Id unitId ) {
        Savepoint sp = Database.setSavepoint();
        try{
            Map<Id, Id> mapExample = new Map<Id, Id>(); // Define a new map
            mapExample.put('a053t000015SvcJAAS','a083t00000XDUSOAA5');                  
            //mapExample.put('a053t000015SvcKAAS', 'a083t00000XDUSPAA5');
            // busco la unidad
            Unit__c unit = [SELECT Module__c, (SELECT Id, Tries__c FROM Unit_Responses__r WHERE Module_Response__r.User__c =: UserInfo.getUserId() ORDER BY Tries__c DESC LIMIT 1 ) FROM Unit__c WHERE Id =: unitId];
            
            //veo si existe un module response
            //primero lo busco en la bd
            Module_Response__c moduleResp;
            try{
                 moduleResp = [SELECT Id FROM Module_Response__c WHERE Module__c=: unit.Module__c AND User__c=: Userinfo.getUserId() AND Status__c = 'In Progress'];
            }catch(Exception e){
            
                //creacion de module response
                 moduleResp = new Module_Response__c(User__c = UserInfo.getUserId(), Module__c = unit.Module__c, Status__c = 'In Progress');
                insert moduleResp;
            }
            
            
            //creacion de unit response
            Unit_Response__c unitResponse = new Unit_Response__c(Unit__c = unitId, Module_Response__c = moduleResp.Id, Status__c = 'Draft');
            
            
            unitResponse.Tries__c = !unit.Unit_Responses__r.isEmpty() ? unit.Unit_Responses__r[0].Tries__c +1:1;
            insert unitResponse;
            
            
            
            //creo questions responses apartir del map que creo con el json
            //Map<Id, Id> quesAnsMap = (Map<Id, Id>)JSON.deserializeStrict(jsonQA, Map<Id,Id>.class);
            List<Question_Response__c> questionResponseList = new List<Question_Response__c>();
            
            for (Id questId : mapExample.keySet()) {
                Question_Response__c questionResponse = new Question_Response__c(Question__c = questId, Unit_Response__c = unitResponse.Id, Option__c = mapExample.get(questId));
                questionResponseList.add(questionResponse);
            }
            insert questionResponseList;
            
            //actualizo el unit response para disparar el proceso de evaluacion
            unitResponse.Status__c = 'Answered';
            update unitResponse;
        }catch(Exception e){
            Database.rollback(sp);
            throw e;
        }
        }
}